### ISSUE TITLE
matchminer-ui hitting matchminer-api: unauthorized access and 404

### ISSUE THREAD

**Issue by cegg** [dfci/matchminer-api#11]
MacOS 10.14.1
conda env with python 2.7
Locally installed matchminer-ui and matchminer-api, started as described in the docs. 
mongo in a container as described in the matchminer-api docs. 

When the UI frontpage loads (8001) it gives correct number of patients (91) so it communicates with mongo OK.

When I inspect network traffic in the browser's development tools, there are several errors trying to hit /api like this:

`http://localhost:8001/api/user/577cf6ef2b9920002cef0337?cacheBuster=1553031094438`

When I hit that in browser, I get 

> "unauthorized access".

Same message if I change the port to 5000 (as it's set in config.json).
Here is the relevant part of `config.json`:
```
  "dev": {
    "ENV": {
      "name": "development",
      "elasticsearch": {
        "host": "http://localhost:9200",
        "proxy": "http://localhost:8001/elasticsearch",
        "index": "matchminer"
      },
      "api": {
        "host": "http://localhost:5000",
        "endpoint": "/api"
      },
      "samlAuthentication": false,
      "devUser": {
        "token" : "some token here,
        "user_id" : "some user id here"
      },
      "certificate" : {
        "key": "../certificates/matchminer.key",
        "cert": "../certificates/matchminer.crt"
      },
```
.....

Both certificates files (matchminer.key and matchminer.crt) are in place 

The messages might be coming from `pymm_run.py` from here:

```
@app.errorhandler(401)
def my_own_error_msg(err):
    return make_response("unauthorized access", 497)
```

What can this "unauthorized access" can by caused by?

There is an option to start matchminer-api with `--no-auth` switch. When I do that, on the front page I get red stripe across with "You are currently not authorized to access this page." message, the patient count is still correct. However, the api calls from the page produce different error: 

e.g. 
`http://localhost:8001/api/user/577cf6ef2b9920002cef0337?cacheBuster=1553032900445`

```
{
    _status: "ERR",
    _error: {
        message: "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.", 
        code: 404
    }
}

```

This happens with both 5000 and 8001 ports

Hitting an API endpoint with no parameters (
`http://localhost:8001/api/user/`) gives this:
```
{
    _items: [ ],
    _links: {
    self: {
         href: "user",
         title: "user"
    },
    parent: {
        href: "/",
        title: "home"
    }
},
    _meta: {
        max_results: 100000,
        total: 0,
        page: 1
    }
}
```

**UPDATE:**
This might be a data issue, user data in particular.  For example, `http://localhost:8001/api/clinical/` being pasted in the browser returns the clinical data ok.
However `http://localhost:8001/api/user/577cf6ef2b9920002cef033` call points at non-existing user id "577cf6ef2b9920002cef033" in a non-existing collection "user". Where are those two entities coming from in the angular frontend? Should "user" collection with that id exist before the ui is started? mongorestore creates only "clinical" and "genomic" collections, no "user".  Or maybe that api call should not get executed on the frontpage load? The problem is this error disables everything in the interface, makes search fields not clickable. 

**UPDATE 2**
The troublesome user API call from the frontpage goes away if:
1. I run matchminer-engine data loading script from matchminer-engine:
`python2.7 matchengine.py load -t examples/trial.example.yml -c examples/clinical.example.csv -g examples/genomic.example.csv --mongo-uri mongodb://localhost:27017` . It does not create any new collections in mongo, but it does bump up the number of patients from 91 to 110
2. restart `python pymm_run.py serve` WITHOUT `--no-auth`

The search still does not work (typing any char in the search fields gives another error) but that's a subject of a different issue. I guess since there is a workaround now this issue can be closed, leaving open just in case if the maintainer would like to comment on my install procedure.

**Comment by ethansiegl** [comment]
closing as it seems this issue resolved. sorry for the delayed response!
