### ISSUE TITLE
matchminer-ui hitting api and elasticsearch: no mapping found for field

### ISSUE THREAD

**Issue by cegg** [dfci/matchminer-api#12]
MacOS 10.14.1
conda env with python 2.7
Locally installed matchminer-ui and matchminer-api, started as described in the docs.
mongo in a container as described in the matchminer-api docs.

When the UI frontpage loads (8001) it gives correct number of patients (91) so it communicates with mongo OK.

When I try to type anything in "Disease Center" search box (or any search box for that matter) in developer tools/network I see these errors:

> Performing suggest! 
> angular.js:11756 POST http://localhost:8001/elasticsearch/matchminer/trial/_search 400 (Bad Request)
> (anonymous) @ angular.js:11756
> sendReq @ angular.js:11517
> serverRequest @ angular.js:11227
> processQueue @ angular.js:15961
> (anonymous) @ angular.js:15977
> $eval @ angular.js:17229
> $digest @ angular.js:17045
> processQueue @ angular-material.js:1734
> (anonymous) @ angular.js:19157
> completeOutstandingRequest @ angular.js:5869
> (anonymous) @ angular.js:6145
> setTimeout (async)
> Browser.self.defer @ angular.js:6143
> timeout @ angular.js:19155
> nextTick @ angular-material.js:1711
> handleAsyncResults @ angular-material.js:26145
> fetchResults @ angular-material.js:26136
> handleQuery @ angular-material.js:26253
> focus @ angular-material.js:25824
> fn @ VM541:4
> expensiveCheckFn @ angular.js:15485
> callback @ angular.js:25018
> $eval @ angular.js:17229
> $apply @ angular.js:17329
> (anonymous) @ angular.js:25023
> dispatch @ jquery.js:5183
> elemData.handle @ jquery.js:4991
> angular.js:13550 Error occurred while searching for suggestions  Error: **[illegal_argument_exception] no mapping found for field [_suggest.disease_center_suggest]**
>     at respond (http://localhost:8001/bower_components/elasticsearch/elasticsearch.angular.js:15491:16)
>     at checkRespForFailure (http://localhost:8001/bower_components/elasticsearch/elasticsearch.angular.js:15450:8)
>     at http://localhost:8001/bower_components/elasticsearch/elasticsearch.angular.js:319:8
>     at processQueue (http://localhost:8001/bower_components/angular/angular.js:15961:28)
>     at http://localhost:8001/bower_components/angular/angular.js:15977:27
>     at Scope.$eval (http://localhost:8001/bower_components/angular/angular.js:17229:28)
>     at Scope.$digest (http://localhost:8001/bower_components/angular/angular.js:17045:31)
>     at Scope.$apply (http://localhost:8001/bower_components/angular/angular.js:17337:24)
>     at http://localhost:8001/bower_components/angular/angular.js:17633:22
>     at completeOutstandingRequest (http://localhost:8001/bower_components/angular/angular.js:5869:10)

I suspect there should be performed some  "elasticsearch configuration"-related step, some mapping / indexing for the elasticsearch.

**Comment by ethansiegl** [comment]
I'm not sure if this is mentioned in the docs but in our production system we use [mongo-connector](https://github.com/yougov/mongo-connector) to sync the trial collection with elasticsearch. you are correct in that you need to first update the analyzers, settings and mappings in the elasticsearch index in order for the syncing to function correctly

**Comment by cegg** [comment]
Recently I am trying to get it all to work without containers, basically I failed to make all those containers to talk to each other the way it's intended. However, I was fiollowing README.md files in all 3 apps, maybe I should have followed this one instead: https://github.com/dfci/matchminer-api/blob/master/DEMO.md ? This is the only one that mentions mongo-connector (and also kibana which is probably another part of the puzzle and I have not installed it yet).

**Comment by ethansiegl** [comment]
ah I forgot about that file but yes. that does explain what to try in more detail I would recommend taking a look and seeing if that helps resolve any of your isses

**Comment by cegg** [comment]
Could you clarify this piece please (the very beginning): 


> See demo_data directory
> Move genomic.bson, clinical.bson, trial.bson, and synonyms.txt to ./demo/matchminer/data/mongo

`demo_data/matchminer` directory contains only `genomic.bson` and `clinical.bson` files. There's no `trial.bson` and `synonyms.txt`

**UPDATE**
According to Elias DeVoe from slack/matchminer-onco-kb, those files do not exist, I need to create my own trial.bson and synonyms.txt is something optional and can be skipped.
