### ISSUE TITLE
Miss matchminer-api/saml/settings_dev.json

### ISSUE THREAD

**Issue by victoria34** [dfci/matchminer-api#3]
Hi,

When I try to access https://localhost:5555, it returns `This site cannot be reached`. I checked log, it displayed the error below. I'm wondering if this file is missed. If yes, could you upload this file? Thanks!

![screen shot 2018-07-02 at 2 42 18 pm](https://user-images.githubusercontent.com/14971266/42180812-9775b434-7e06-11e8-8c14-b90dd8ca0840.png)

**Comment by jim-bo** [comment]
@victoria34 are you trying to connect MM to a SAML authentication end point? I'll have to confer with @zwiesler on this because if you are running the application without authentication this file shouldn't be required.

**Comment by ethansiegl** [comment]
closing
