### ISSUE TITLE
Link to demo data download gives 404

### ISSUE THREAD

**Issue by cegg** [dfci/matchminer-api#5]
Deco docs: 
Link https://drive.google.com/open?id=0B334b-HHVrwGc3djZUdvMktNekU gives 404

**Comment by ethansiegl** [comment]
While I do see that the link is broken, I don't see where you found that link? Not sure what data you were expecting to find there?

EDIT: Nevermind found the link in the repo. It's outdated.. will post the updated URL when I can find

**Comment by ethansiegl** [comment]
demo data has been added to the repo. closing issue.
